### ISSUE TITLE
Hidden menu becomes visible when window is smaller than 1199 x 658

### ISSUE THREAD

**Issue by painkil3r** [thetomester13/homepage#13]
Hello,

Love the software. Looks really good.

Just noticing the hidden menu becomes visible when un-maximising the browser window and scaling it down. Around 1199 x 658 the menu appears without any interaction with the unlock pattern. 

Also, for us Nginx users, the .htaccess file is not relevant. Adding a security section to the Readme.md mentioning to hide your config.json would be a useful addition for new comers. The following will help block access to it.

```
location = /config.json {
		return 403;
	}
```

Cheers,

**Comment by tomershvueli** [comment]
Thanks for the notes, @painkil3r ! 
I'm not seeing the menu appear at that resolution, but the menu hamburger icon appears then, so if a user is on mobile, they can use that to toggle the menu instead of a keyboard pattern. As for the security section of the README, would you want to create a PR for it? I'm not familiar with Nginx, so your notes might be better than something I could come up with!
