### ISSUE TITLE
Change color of highlighted icons

### ISSUE THREAD

**Issue by lentidas** [thetomester13/homepage#15]
First of all, thanks a lot by this simple yet really nice project of yours.

What brings me here is more of a feature request / personal preference than an issue... I'm a little annoyed by the green when the mouse is hovering over an icon. I'm more inclined to use a light blue or something along those lines.

Could you please explain me how the color is defined and point me to the code on the repository so I can thinker with those settings a bit?

**Comment by tomershvueli** [comment]
Thanks for the kind words! 

Sure, the color is defined in the [main.css file on line 19](https://github.com/tomershvueli/homepage/blob/master/hp_assets/css/main.css#L19). You can feel free to change it there. Although I like the idea of the hover color being a config variable, if you're feeling up to it, you can submit a PR to take care of that! Otherwise, I might do that some point soon anyway. Thanks for bringing this to my attention.

**Comment by lentidas** [comment]
I'm pretty basic around code, I wouldn't be able to help you and submit a PR. I can understand how things work, like in this case I can easily change a few lines as long anyone points me in the right direction, but I've never written something from scratch 😉

Thanks for the help and keep up the good work!

**Comment by tomershvueli** [comment]
@lentidas no problem. If you pull the latest (b714cca21fd75b45aef21dafc01c1364996f0d8d) you should be able to configure the hover color for links in the standard config file.
