### ISSUE TITLE
Unsplash no longer viable option

### ISSUE THREAD

**Issue by zerosonesfun** [thetomester13/homepage#24]
Unsplash no longer lets you use their API for something like this. You may get away with it for a while but there is a risk of them shutting it down. If they don’t, you are limited to 50 image impressions per hour with no approvals from them. If you apply for their normal free API tier which gives you thousands of image impressions (I don’t recall the exact number), although it is free, most likely the reviewer will not approve your “app” since they only like people using their API if you’re going to offer something different from what their site offers. They consider this, a rotating image, not different enough.

**Comment by tomershvueli** [comment]
Homepage isn't meant to be an image-heavy application necessarily. And since each instance is self hosted, it's up to the developers themselves to figure out how or where to get their background images from - I just figured Unsplash was a good place to start and provide a default for users. Even with 50 images / hour, that's still a new image request every 90 seconds. I wouldn't say that Unsplash is no longer viable. 

Do you have a suggestion for a replacement service? Alternatively, I could change the default `time_to_refresh_bg` config variable to 90 seconds, meaning a normal user wouldn't go over the free app allotment.

**Comment by zerosonesfun** [comment]
Sorry, I don’t know of a replacement service. The problem is that by default you get Unsplash’s “demo” API. Meant for testing only. If anyone applies for Unsplash’s normal production API Unsplash will shut it down. That’s what happened to me. I wasn’t trying to abuse their API or place this homepage within a traffic heavy site. I just thought, “I’ll apply for the production API... why not? It’s free.” I didn’t realize Unsplash would then shut it down after seeing it was a rotating image situation.

But, it’s fine for you to keep this as-is. If nothing else as an example that you can use some kind of API for the background images. Maybe some type of note in the readme would be helpful though. I’m sure I won’t be the only person who assumes since Unsplash’s API is free, they are okay with this set up. Even if this is installed solely as intended (a personal homepage) as soon as you apply for the API or probably at any point really, Unsplash may shut it down.

**Comment by tomershvueli** [comment]
@zerosonesfun I see. Sorry you came across that. It's a bit absurd to think that they would revoke your API key entirely instead of simply denying the Production key. I'd imagine you can probably create another one under a separate account and keep it at demo level for this purpose. 

FWIW, I added a note (22e7d066fca3436a75f1d2f611f9c0896e39a144) warning future users to not try and go down the same path. Thanks for the heads up!
